export const blankTrip = {
  title: "",
  description: "",
  image: "",
  startDate: "2021-07-01",
  endDate: "2021-07-02",
  area: "",
  regs: "",
  muster: "",
  distance: 0,
  elevation: 0,
  groupSize: 0,
  gearList: [],
  team: [],
  report: "",
}
